[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/places"
  to = "/.netlify/functions/places"
  status = 200

[[redirects]]
  from = "/api/pick"
  to = "/.netlify/functions/pick"
  status = 200
