/* IDKPicker i18n — loads translations, applies them to [data-i18n*] elements,
   and exposes window.I18N.t(key, vars). English source text lives inline in
   index.html (<script type="application/json" id="i18n-en">) — edit it there.
   Built-in files exist for STATIC languages; any other language is translated
   by AI via /api/translate and cached (server + this browser). */
(function () {
  var STATIC = ['en', 'es', 'fr', 'de', 'pt'];
  var RTL = ['ar', 'he', 'fa', 'ur', 'ps', 'yi', 'ckb', 'sd', 'ug'];
  // Languages offered in the picker (native names are generated by the browser)
  var PICKER = ['en','es','fr','de','pt','it','nl','pl','ru','uk','tr','ar','he','fa','hi','bn','ur','ta','te',
    'zh-Hans','zh-Hant','ja','ko','vi','th','id','ms','fil','sv','da','nb','fi','el','cs','sk','hu','ro','bg',
    'hr','sr','sl','lt','lv','et','is','ga','ca','eu','gl','sw','am','zu','af','ne','si','km','my','ka','hy','az','kk','uz','mn'];

  function norm(code) {
    if (!code) return 'en';
    var c = String(code).replace('_', '-');
    var parts = c.split('-'), base = parts[0].toLowerCase();
    if (base === 'zh') {
      var rest = c.toLowerCase();
      return /hant|-tw|-hk|-mo/.test(rest) ? 'zh-Hant' : 'zh-Hans';
    }
    if (base === 'no' || base === 'nn') return 'nb';
    if (base === 'tl') return 'fil';
    if (base === 'iw') return 'he';
    if (base === 'in') return 'id';
    return /^[a-z]{2,3}$/.test(base) ? base : 'en';
  }
  function read(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
  function store(k, v) { try { v == null ? localStorage.removeItem(k) : localStorage.setItem(k, v); } catch (e) {} }
  // djb2 — same function runs on the server to version the cache
  function hash(s) { var h = 5381; for (var i = 0; i < s.length; i++) h = ((h << 5) + h + s.charCodeAt(i)) | 0; return (h >>> 0).toString(36); }

  var saved = read('lang');
  var lang = norm(saved || (navigator.languages && navigator.languages[0]) || navigator.language);
  var enText = document.getElementById('i18n-en').textContent;
  var EN = JSON.parse(enText), dict = {}, listeners = [], ready;

  function t(key, vars) {
    var s = (dict[key] != null ? dict[key] : EN[key]);
    if (s == null) return key;
    if (vars) s = s.replace(/\{(\w+)\}/g, function (m, k) { return vars[k] != null ? vars[k] : m; });
    return s;
  }
  function apply(root) {
    root = root || document;
    root.querySelectorAll('[data-i18n]').forEach(function (el) { el.textContent = t(el.getAttribute('data-i18n')); });
    root.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var html = t(el.getAttribute('data-i18n-html'));
      if (el.hasAttribute('data-i18n-icon')) html = html.replace('{icon}', document.getElementById(el.getAttribute('data-i18n-icon')).innerHTML);
      el.innerHTML = html;
    });
    root.querySelectorAll('[data-i18n-placeholder]').forEach(function (el) { el.placeholder = t(el.getAttribute('data-i18n-placeholder')); });
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL.indexOf(lang.split('-')[0]) >= 0 ? 'rtl' : 'ltr';
  }
  function setDict(d) {
    dict = d || {};
    apply();
    listeners.forEach(function (fn) { try { fn(lang); } catch (e) {} });
  }
  function nativeName(code, inLang) {
    try { var n = new Intl.DisplayNames([inLang || code], { type: 'language' }).of(code); return n.charAt(0).toLocaleUpperCase(code) + n.slice(1); }
    catch (e) { return code; }
  }
  function langName(code, inLang) {
    try { return new Intl.DisplayNames([inLang || code], { type: 'language' }).of(code); } catch (e) { return code; }
  }
  // Google APIs want zh-CN / zh-TW, not script subtags
  function googleLang() { return lang === 'zh-Hans' ? 'zh-CN' : lang === 'zh-Hant' ? 'zh-TW' : lang === 'nb' ? 'no' : lang; }
  function englishName() { return nativeName(lang, 'en'); }

  async function loadDict(code) {
    if (code === 'en') return {};
    var key = 'i18n:' + code, cached = null;
    try { cached = JSON.parse(read(key) || 'null'); } catch (e) {}
    if (cached && cached.v === hash(enText.trim())) return cached.d;
    var url = STATIC.indexOf(code) >= 0 ? '/i18n/' + code + '.json' : '/api/translate?lang=' + encodeURIComponent(code) + '&v=' + hash(enText.trim());
    var res = await fetch(url);
    if (!res.ok) throw new Error('translation ' + res.status);
    var d = await res.json();
    // static files may lag behind en.json — only cache them if complete
    var complete = Object.keys(EN).every(function (k) { return d[k] != null; });
    if (complete || STATIC.indexOf(code) < 0) store(key, JSON.stringify({ v: hash(enText.trim()), d: d }));
    return d;
  }

  ready = (async function () {
    if (document.readyState === 'loading') await new Promise(function (r) { document.addEventListener('DOMContentLoaded', r); });
    if (lang === 'en') { apply(); return; }
    // Show cached/static quickly; don't hold the page hostage to a slow AI translation
    document.documentElement.classList.add('i18n-pending');
    var reveal = setTimeout(function () { document.documentElement.classList.remove('i18n-pending'); }, 1200);
    try { setDict(await loadDict(lang)); }
    catch (e) { console.warn('[i18n] falling back to English:', e.message); lang = 'en'; setDict({}); }
    clearTimeout(reveal);
    document.documentElement.classList.remove('i18n-pending');
  })();

  var switching = Promise.resolve();
  function setLang(code) {
    store('lang', code === 'auto' ? null : code);
    var next = code === 'auto' ? norm((navigator.languages && navigator.languages[0]) || navigator.language) : norm(code);
    switching = loadDict(next).then(function (d) { lang = next; setDict(d); })
      .catch(function (e) { console.warn('[i18n] could not switch:', e.message); });
    return switching;
  }

  window.I18N = {
    t: t, apply: apply, ready: ready, norm: norm, nativeName: nativeName, langName: langName, englishName: englishName,
    googleLang: googleLang, setLang: setLang, picker: PICKER,
    get lang() { return lang; }, get explicit() { return !!read('lang'); },
    onChange: function (fn) { listeners.push(fn); },
    preview: loadDict // used to show the "switch language?" prompt in the target language
  };
})();
